### ISSUE TITLE
Is this or windows, linux, or both? and which version of python 2 or 3?

### ISSUE THREAD

**Issue by wm2017email** [corna/me_cleaner#54]
Hi,

Just a suggestion to save time for people...

Update readme to state which operating system you have run and tested the script under (example: linux or windows, or both)  And which version of python you are using, example python 2 or python 3, or both.

Bill

**Comment by corna** [comment]
Hi,

I didn't add it in the readme because it's both python 2 and python 3 compatible and it doesn't require any external package, which means that it's not bound to any particular OS: as long as you have a relatively recent version of python, this script works.

I'll add a note in the wiki, thank you for the suggestion.
